import type { EnumOrStringLiteralTypes } from '../../types';

export enum Cursor {
  ALIAS = 'alias',
  ALL_SCROLL = 'all-scroll',
  AUTO = 'auto',
  CELL = 'cell',
  COL_RESIZE = 'col-resize',
  CONTEXT_MENU = 'context-menu',
  COPY = 'copy',
  CROSSHAIR = 'crosshair',
  DEFAULT = 'default',
  E_RESIZE = 'e-resize',
  EW_RESIZE = 'ew-resize',
  GRAB = 'grab',
  GRABBING = 'grabbing',
  HELP = 'help',
  INHERIT = 'inherit',
  MOVE = 'move',
  N_RESIZE = 'n-resize',
  NE_RESIZE = 'ne-resize',
  NESW_RESIZE = 'nesw-resize',
  NO_DROP = 'no-drop',
  NONE = 'none',
  NOT_ALLOWED = 'not-allowed',
  NS_RESIZE = 'ns-resize',
  NW_RESIZE = 'nw-resize',
  NWSE_RESIZE = 'nwse-resize',
  POINTER = 'pointer',
  PROGRESS = 'progress',
  ROW_RESIZE = 'row-resize',
  S_RESIZE = 's-resize',
  SE_RESIZE = 'se-resize',
  SW_RESIZE = 'sw-resize',
  TEXT = 'text',
  VERTICAL_TEXT = 'vertical-text',
  W_RESIZE = 'w-resize',
  WAIT = 'wait',
  ZOOM_IN = 'zoom-in',
  ZOOM_OUT = 'zoom-out',
}

export type CursorType = EnumOrStringLiteralTypes<Cursor>;
