name: CI - Push

permissions:
  packages: write
  contents: read
  pull-requests: read

on:
  push:
    branches:
      - main

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest

    steps:
    - name: Git Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        fetch-tags: false
        set-safe-directory: true

  setup-workspace:
    name: Setup - Workspace
    needs: checkout
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/bake
        with:
          target: setup-workspace
          cache-registry: true

  build-workspace:
    name: Build - Workspace
    needs: setup-workspace
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/bake
        with:
          target: build
          cache-registry: true
