name: CI - Pull Request

permissions:
  packages: write
  contents: read
  pull-requests: read

on:
  pull_request:
    branches:
      - main

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest

    steps:
    - name: Git Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        fetch-tags: false
        set-safe-directory: true

  setup-workspace:
    name: Setup - Workspace
    needs: checkout
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/bake
        with:
          target: setup-workspace
          cache-registry: true

  build-workspace:
    name: Build - Workspace
    needs: setup-workspace
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/bake
        with:
          target: build
          cache-registry: true

  lint-eslint:
    name: Lint - ESLint
    needs: setup-workspace
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/bake
        with:
          target: lint-eslint

  lint-prettier:
    name: Lint - Prettier
    needs: setup-workspace
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/bake
        with:
          target: lint-prettier

  test-jest:
    name: Test - Jest
    needs: build-workspace
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/bake
        with:
          target: test-jest

  test-playwright:
    name: Test - Playwright
    needs: build-workspace
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/bake
        with:
          target: test-playwright
